services:
  lorebot-api:
    build: .
    image: cperkins577/lorebot-api:latest
    platform: linux/arm64
    container_name: lorebot_api
    command: node src/api/server.js
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always

  discord-bot:
    build: .
    image: cperkins577/lorebot:latest
    platform: linux/arm64
    container_name: lorebot
    command: node src/bot/index.js
    env_file:
      - .env
    restart: always
